ll/dashboard/user/views.py
# This file is part of Living Labs Challenge, see http://living-labs.net.
#
# Living Labs Challenge is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Living Labs Challenge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, request, render_template, flash, g, session, \
                    redirect, url_for
from werkzeug import check_password_hash

from .. import core, requires_login
from forms import LoginForm, RegisterForm, ForgotForm

mod = Blueprint('user', __name__, url_prefix='/user')


@mod.route('/me/')
@requires_login
def home():
    return render_template("user/profile.html", user=g.user)


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = core.user.get_user_by_email(form.email.data)
        # we use werzeug to validate user's password
        if user and check_password_hash(user["password"], form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['key'] = user["_id"]
            flash('Welcome %s' % user["teamname"], 'alert-success')
            return redirect(url_for('user.home'))
        flash('Wrong email or password', 'alert-info')
    return render_template("user/login.html", form=form, user=g.user)


@mod.route('/logout/', methods=['GET'])
def logout():
    """
    Logout
    """
    g.user = None
    del session['key']
    return redirect("/")


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        try:
            user = core.user.new_user(form.teamname.data, form.email.data,
                                      password=form.password.data)
        except Exception, e:
            flash(str(e), 'alert-warning')
            return render_template("user/register.html", form=form,
                                   user=g.user)
        key = user["_id"]
        session['key'] = key
        flash('Thanks for registering. Your key is: %s' % key, 'alert-success')
        # redirect user to the 'home' method of the user module.
        return redirect(url_for('user.home'))
    return render_template("user/register.html", form=form, user=g.user)


@mod.route('/forgot/', methods=['GET', 'POST'])
def forgot():
    form = ForgotForm(request.form)
    if form.validate_on_submit():
        try:
            core.user.reset_password(form.email.data)
        except Exception, e:
            flash(str(e), 'alert-warning')
            return redirect(url_for('user.forgot'))
        flash('A new password has been sent to %s.' % form.email.data,
              'alert-success')
        return redirect("/")
    return render_template("user/forgot.html", form=form, user=g.user)

ll/dashboard/templates/base.html
{# This file is part of Living Labs Challenge, see http://living-labs.net.
 #
 # Living Labs Challenge is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Living Labs Challenge is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
 # You should have received a copy of the GNU Lesser General Public License
 # along with Living Labs Challenge. If not, see <http://www.gnu.org/licenses/>.
 #}
<html>
  <head>
    <title>{% block title %}Living Labs Dashboard{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/main.css" />
    {% endblock %}
    {% block script %}
    <script src="/static/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    {% endblock %}
  </head>
  <body>
  	<div id="navbar" class="navbar navbar-default navbar-fixed-top">
	    <div class="container">
	      <div class="navbar-header">
	        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand" href="#">
	          Living Labs Challenge</a>
	        <span class="navbar-text navbar-version pull-left"><b></b></span>
	      </div>
			<div class="collapse navbar-collapse nav-collapse">
			  <ul class="nav navbar-nav">
			    <li class="divider-vertical"></li>
			        <li><a href="http://living-labs.net/challenge/">Website</a></li>
			        <li><a href="/">Dashboard</a></li>
			        <li><a href="http://doc.living-labs.net/">Documentation</a></li>
			</div>
	    </div>
	</div>
<div class="container">
<div class="row">
<div class="col-md-9 dmbs-main">
	      <div class="navbar-header">
	        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand" href="/">
	          Dashboard</a>
	        <span class="navbar-text navbar-version pull-left"><b></b></span>
	      </div>
	<ul class="nav nav-tabs">
	  <li {% if request.path == "/" %}class="active"{% endif %}><a href="/">Home</a></li>
	  <li {% if request.path.startswith("/participant") %}class="active"{% endif %}><a href="/participant">Participants</a></li>
	  <li {% if request.path.startswith("/site") %}class="active"{% endif %}><a href="/site">Sites</a></li>
	  {% if user %}
	  <li class="dropdown {% if request.path.startswith("/user") %}active{% endif %}">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	    <span class="glyphicon glyphicon-user"></span> {{ user.teamname }}<span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li><a href="/user/me">Profile</a></li>
	      <li class="divider"></li>
	      <li><a href="/user/logout"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
	    </ul>
	  </li>
	  {% else %}
	  <li {% if request.path.startswith("/user/login") %}class="active"{% endif %}>  
	  <a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
	  </li>
	  <li {% if request.path.startswith("/user/register") %}class="active"{% endif %}>
	  <a href="{{ url_for('user.register') }}"><span class="glyphicon glyphicon-user"></span> Register</a>
	  </li>
	  {% endif %}
	</ul>
	<div class="page-header">
    	<h1>{% block header %}Home{% endblock %}</h1>
    </div>
    <div id="messages-wrap">
      <div id="messages">
        {% for category, msg in get_flashed_messages(with_categories=true) %}
          <p class="alert {{ category }}">{{ msg }}</p>
        {% endfor %}
      </div>
    </div>
    <div id="content">
    {% block content %}    
    Welcome to the dashboard of the Living Labs Challenge.   
    {% endblock %}
    </div>
 </div>
 </div>
 </div>
 <footer class="footer">
  <div class="container">
    <p class="text-muted">
        &copy; Copyright 2014, Living Labs.<br/>
    </p>
  </div>
</footer>
  </body>
</html>